/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jiahaodong' at '16-12-4 上午11:27' with Gradle 2.14.1
 *
 * @author jiahaodong, @date 16-12-4 上午11:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
